<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-488FP15" ignored="0" name="IETest" tests="3" failures="2" timestamp="26 Jun 2019 06:21:19 GMT" time="183.718" errors="0">
  <testcase name="ValidLoginLogout" time="74.997" classname="Com.ActiTime.Tests.ValidLoginLogoutTest"/>
  <testcase name="InvalidLogin" time="82.144" classname="Com.ActiTime.Tests.InvalidLoginTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Com.ActiTime.Generic.BasePage.verifyElement(BasePage.java:42)
at Com.ActiTime.Pages.actiTIMELoginPage.verifyErrorMsg(actiTIMELoginPage.java:39)
at Com.ActiTime.Tests.InvalidLoginTest.InvalidLogin(InvalidLoginTest.java:30)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- InvalidLogin -->
  <testcase name="Verifyversion" time="0.563" classname="Com.ActiTime.Tests.VerifyversionTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [actiTIME 2019.2 Pro] but found [actiTIME 2019.3 Pro]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [actiTIME 2019.2 Pro] but found [actiTIME 2019.3 Pro]
at Com.ActiTime.Tests.VerifyversionTest.Verifyversion(VerifyversionTest.java:24)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Verifyversion -->
</testsuite> <!-- IETest -->
